name: "Reusable Workflow using Composite Action"

on:
  #[push]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Use Composite Action - Publish to Docker Registry
        # You may pin to the exact commit or the version.
        # uses: Cschau0701vip/CompositeAction@1ecac96929f8b823e3a16056c463dd4bb1552dfa
        uses: Cschau0701vip/CompositeAction@v2
        with:
          # Username of the Docker registry
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          # Password of the Docker registry
          registry_password: ${{ secrets.REGISTRY_PASSWORD }} 
          # Name of the Docker image to push
          image_name: ${{ vars.IMAGE_NAME }}
          # Tag of the Docker image. Default: Latest
          image_tag: $GITHUB_RUN_NUMBER # optional
          
  test:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Docker Setup Buildx
        # uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7
        uses: docker/setup-buildx-action@v2.4.1
        
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          #registry: # optional
          # Username used to log against the Docker registry
          username: ${{ secrets.REGISTRY_USERNAME }} # optional
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.REGISTRY_PASSWORD }}  # optional
          # Specifies whether the given registry is ECR (auto, true or false)
          ecr: false # optional, default is auto
          # Log out from the Docker registry at the end of a job
          logout: true # optional, default is true
    
      - name: Run Docker Container from Image
        run: |
          sudo service docker start
          sudo docker pull ${{ secrets.REGISTRY_USERNAME }}/${{ vars.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
          sudo docker run ${{ secrets.REGISTRY_USERNAME }}/${{ vars.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
